// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PublisherData;

#nullable disable

namespace PublisherData.Migrations
{
    [DbContext(typeof(PubContext))]
    partial class PubContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PublisherDomain.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "FirstName1",
                            LastName = "LastName1"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "FirstName2",
                            LastName = "LastName2"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "FirstName3",
                            LastName = "LastName3"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "FirstName4",
                            LastName = "LastName4"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "FirstName5",
                            LastName = "LastName5"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "FirstName6",
                            LastName = "LastName6"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "FirstName7",
                            LastName = "LastName7"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "FirstName8",
                            LastName = "LastName8"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "FirstName9",
                            LastName = "LastName9"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "FirstName10",
                            LastName = "LastName10"
                        });
                });

            modelBuilder.Entity("PublisherDomain.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"), 1L, 1);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookId");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            AuthorId = 1,
                            BasePrice = 100m,
                            PublishDate = new DateTime(2001, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book_1_by_Author_1"
                        },
                        new
                        {
                            BookId = 2,
                            AuthorId = 1,
                            BasePrice = 100m,
                            PublishDate = new DateTime(2002, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book_2_by_Author_1"
                        },
                        new
                        {
                            BookId = 3,
                            AuthorId = 1,
                            BasePrice = 100m,
                            PublishDate = new DateTime(2003, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book_3_by_Author_1"
                        },
                        new
                        {
                            BookId = 4,
                            AuthorId = 1,
                            BasePrice = 100m,
                            PublishDate = new DateTime(2004, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book_4_by_Author_1"
                        },
                        new
                        {
                            BookId = 5,
                            AuthorId = 1,
                            BasePrice = 100m,
                            PublishDate = new DateTime(2005, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book_5_by_Author_1"
                        },
                        new
                        {
                            BookId = 6,
                            AuthorId = 2,
                            BasePrice = 100m,
                            PublishDate = new DateTime(2002, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book_1_by_Author_2"
                        },
                        new
                        {
                            BookId = 7,
                            AuthorId = 2,
                            BasePrice = 100m,
                            PublishDate = new DateTime(2004, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book_2_by_Author_2"
                        },
                        new
                        {
                            BookId = 8,
                            AuthorId = 2,
                            BasePrice = 100m,
                            PublishDate = new DateTime(2006, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book_3_by_Author_2"
                        },
                        new
                        {
                            BookId = 9,
                            AuthorId = 2,
                            BasePrice = 100m,
                            PublishDate = new DateTime(2008, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book_4_by_Author_2"
                        },
                        new
                        {
                            BookId = 10,
                            AuthorId = 2,
                            BasePrice = 100m,
                            PublishDate = new DateTime(2010, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book_5_by_Author_2"
                        },
                        new
                        {
                            BookId = 11,
                            AuthorId = 3,
                            BasePrice = 100m,
                            PublishDate = new DateTime(2003, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book_1_by_Author_3"
                        },
                        new
                        {
                            BookId = 12,
                            AuthorId = 3,
                            BasePrice = 100m,
                            PublishDate = new DateTime(2006, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book_2_by_Author_3"
                        },
                        new
                        {
                            BookId = 13,
                            AuthorId = 3,
                            BasePrice = 100m,
                            PublishDate = new DateTime(2009, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book_3_by_Author_3"
                        },
                        new
                        {
                            BookId = 14,
                            AuthorId = 3,
                            BasePrice = 100m,
                            PublishDate = new DateTime(2012, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book_4_by_Author_3"
                        },
                        new
                        {
                            BookId = 15,
                            AuthorId = 3,
                            BasePrice = 100m,
                            PublishDate = new DateTime(2015, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book_5_by_Author_3"
                        },
                        new
                        {
                            BookId = 16,
                            AuthorId = 4,
                            BasePrice = 100m,
                            PublishDate = new DateTime(2004, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book_1_by_Author_4"
                        },
                        new
                        {
                            BookId = 17,
                            AuthorId = 4,
                            BasePrice = 100m,
                            PublishDate = new DateTime(2008, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book_2_by_Author_4"
                        },
                        new
                        {
                            BookId = 18,
                            AuthorId = 4,
                            BasePrice = 100m,
                            PublishDate = new DateTime(2012, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book_3_by_Author_4"
                        },
                        new
                        {
                            BookId = 19,
                            AuthorId = 4,
                            BasePrice = 100m,
                            PublishDate = new DateTime(2016, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book_4_by_Author_4"
                        },
                        new
                        {
                            BookId = 20,
                            AuthorId = 4,
                            BasePrice = 100m,
                            PublishDate = new DateTime(2020, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book_5_by_Author_4"
                        },
                        new
                        {
                            BookId = 21,
                            AuthorId = 5,
                            BasePrice = 100m,
                            PublishDate = new DateTime(2005, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book_1_by_Author_5"
                        },
                        new
                        {
                            BookId = 22,
                            AuthorId = 5,
                            BasePrice = 100m,
                            PublishDate = new DateTime(2010, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book_2_by_Author_5"
                        },
                        new
                        {
                            BookId = 23,
                            AuthorId = 5,
                            BasePrice = 100m,
                            PublishDate = new DateTime(2015, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book_3_by_Author_5"
                        },
                        new
                        {
                            BookId = 24,
                            AuthorId = 5,
                            BasePrice = 100m,
                            PublishDate = new DateTime(2020, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book_4_by_Author_5"
                        },
                        new
                        {
                            BookId = 25,
                            AuthorId = 5,
                            BasePrice = 100m,
                            PublishDate = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book_5_by_Author_5"
                        },
                        new
                        {
                            BookId = 26,
                            AuthorId = 6,
                            BasePrice = 100m,
                            PublishDate = new DateTime(2006, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book_1_by_Author_6"
                        },
                        new
                        {
                            BookId = 27,
                            AuthorId = 6,
                            BasePrice = 100m,
                            PublishDate = new DateTime(2012, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book_2_by_Author_6"
                        },
                        new
                        {
                            BookId = 28,
                            AuthorId = 6,
                            BasePrice = 100m,
                            PublishDate = new DateTime(2018, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book_3_by_Author_6"
                        },
                        new
                        {
                            BookId = 29,
                            AuthorId = 6,
                            BasePrice = 100m,
                            PublishDate = new DateTime(2024, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book_4_by_Author_6"
                        },
                        new
                        {
                            BookId = 30,
                            AuthorId = 6,
                            BasePrice = 100m,
                            PublishDate = new DateTime(2030, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book_5_by_Author_6"
                        },
                        new
                        {
                            BookId = 31,
                            AuthorId = 7,
                            BasePrice = 100m,
                            PublishDate = new DateTime(2007, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book_1_by_Author_7"
                        },
                        new
                        {
                            BookId = 32,
                            AuthorId = 7,
                            BasePrice = 100m,
                            PublishDate = new DateTime(2014, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book_2_by_Author_7"
                        },
                        new
                        {
                            BookId = 33,
                            AuthorId = 7,
                            BasePrice = 100m,
                            PublishDate = new DateTime(2021, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book_3_by_Author_7"
                        },
                        new
                        {
                            BookId = 34,
                            AuthorId = 7,
                            BasePrice = 100m,
                            PublishDate = new DateTime(2028, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book_4_by_Author_7"
                        },
                        new
                        {
                            BookId = 35,
                            AuthorId = 7,
                            BasePrice = 100m,
                            PublishDate = new DateTime(2035, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book_5_by_Author_7"
                        },
                        new
                        {
                            BookId = 36,
                            AuthorId = 8,
                            BasePrice = 100m,
                            PublishDate = new DateTime(2008, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book_1_by_Author_8"
                        },
                        new
                        {
                            BookId = 37,
                            AuthorId = 8,
                            BasePrice = 100m,
                            PublishDate = new DateTime(2016, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book_2_by_Author_8"
                        },
                        new
                        {
                            BookId = 38,
                            AuthorId = 8,
                            BasePrice = 100m,
                            PublishDate = new DateTime(2024, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book_3_by_Author_8"
                        },
                        new
                        {
                            BookId = 39,
                            AuthorId = 8,
                            BasePrice = 100m,
                            PublishDate = new DateTime(2032, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book_4_by_Author_8"
                        },
                        new
                        {
                            BookId = 40,
                            AuthorId = 8,
                            BasePrice = 100m,
                            PublishDate = new DateTime(2040, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book_5_by_Author_8"
                        },
                        new
                        {
                            BookId = 41,
                            AuthorId = 9,
                            BasePrice = 100m,
                            PublishDate = new DateTime(2009, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book_1_by_Author_9"
                        },
                        new
                        {
                            BookId = 42,
                            AuthorId = 9,
                            BasePrice = 100m,
                            PublishDate = new DateTime(2018, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book_2_by_Author_9"
                        },
                        new
                        {
                            BookId = 43,
                            AuthorId = 9,
                            BasePrice = 100m,
                            PublishDate = new DateTime(2027, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book_3_by_Author_9"
                        },
                        new
                        {
                            BookId = 44,
                            AuthorId = 9,
                            BasePrice = 100m,
                            PublishDate = new DateTime(2036, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book_4_by_Author_9"
                        },
                        new
                        {
                            BookId = 45,
                            AuthorId = 9,
                            BasePrice = 100m,
                            PublishDate = new DateTime(2045, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book_5_by_Author_9"
                        },
                        new
                        {
                            BookId = 46,
                            AuthorId = 10,
                            BasePrice = 100m,
                            PublishDate = new DateTime(2010, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book_1_by_Author_10"
                        },
                        new
                        {
                            BookId = 47,
                            AuthorId = 10,
                            BasePrice = 100m,
                            PublishDate = new DateTime(2020, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book_2_by_Author_10"
                        },
                        new
                        {
                            BookId = 48,
                            AuthorId = 10,
                            BasePrice = 100m,
                            PublishDate = new DateTime(2030, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book_3_by_Author_10"
                        },
                        new
                        {
                            BookId = 49,
                            AuthorId = 10,
                            BasePrice = 100m,
                            PublishDate = new DateTime(2040, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book_4_by_Author_10"
                        },
                        new
                        {
                            BookId = 50,
                            AuthorId = 10,
                            BasePrice = 100m,
                            PublishDate = new DateTime(2050, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book_5_by_Author_10"
                        });
                });

            modelBuilder.Entity("PublisherDomain.Book", b =>
                {
                    b.HasOne("PublisherDomain.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("PublisherDomain.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
